### ISSUE TITLE
疑似是愛梅斯新加入的暱稱導致程式報錯

### ISSUE THREAD

**Issue by negimiku1227** [Ice9Coffee/LandosolRoster#22]
昨日啟動PrincessStudio時，程式閃退並留下以下錯誤訊息
```
System.ArgumentException: An item with the same key has already been added. Key: 菲欧
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at PCRApi.Form.HORIZONTAL_BOX_OPPONENT.<>c__DisplayClass2_1.<.ctor>b__11(Object y) in C:\Users\_\source\repos\PrincessStudio_JP\PCRApi\Form\HORIZONTAL\BOX_OPPONENT.cs:line 75
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PCRApi.Form.HORIZONTAL_BOX_OPPONENT.<>c__DisplayClass2_0.<.ctor>b__3(KeyValuePair`2 x) in C:\Users\_\source\repos\PrincessStudio_JP\PCRApi\Form\HORIZONTAL\BOX_OPPONENT.cs:line 75
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PCRApi.Form.HORIZONTAL_BOX_OPPONENT..ctor() in C:\Users\_\source\repos\PrincessStudio_JP\PCRApi\Form\HORIZONTAL\BOX_OPPONENT.cs:line 75
   at PCRApi.Form.PrincessStudio..ctor() in C:\Users\_\source\repos\PrincessStudio_JP\PCRApi\Form\PrincessStudio.cs:line 58
   at PCRApi.Form.PrincessStudio.get_Instance() in C:\Users\_\source\repos\PrincessStudio_JP\PCRApi\Form\PrincessStudio.cs:line 21
   at PCRApi.Program.Main(String[] args) in C:\Users\_\source\repos\PrincessStudio_JP\PCRApi\Program.cs:line 257
```

查看了_pcr_data.py，看到了一行
```
1230: ["爱梅斯", "アメス", "Amesu", "菲欧", "爱美斯", "艾美斯", "艾梅斯"],
```
以及
```
1901: ["菲欧", "フィオ", "Fio"],
```

想詢問是否是因此原因造成閃退，感謝

**Comment by cc004** [comment]
@krulci
